class HTTPExceptionDetail:
    CAPTCHA_IS_NOT_VALID = "captcha is not valid"
    EMAIL_ALREADY_EXISTS = "email already exists"
    USERNAME_ALREADY_EXISTS = "username already exists"
    NO_EMAIL = "no email"
    EMAIL_WAS_ALREADY_VERIFIED = "email was already verified"
    SAME_USERNAME = "same username"
    SAME_EMAIL = "same email"
    PASSWORD_ALREADY_EXISTS = "password already exists"
    PASSWORD_IS_NOT_SET = "password is not set"
    INCORRECT_OLD_PASSWORD = "incorrect old password"
