class Detail:
    INVALID_CAPTCHA = "invalid captcha"
    EMAIL_ALREADY_EXISTS = "email already exists"
    USERNAME_ALREADY_EXISTS = "username already exists"
    SAME_USERNAME = "same username"
    PASSWORD_ALREADY_EXISTS = "password already exists"
    PASSWORD_NOT_SET = "password not set"
    INCORRECT_OLD_PASSWORD = "incorrect old password"
    USER_NOT_ACTIVE = "user not active"
    WRONG_TOKEN_TYPE = "wrong token type"
    TOKEN_ALREADY_USED = "token already used"
    EMAIL_ALREADY_VERIFIED = "email already verified"
    EMAIL_MISMATCH = "email mismatch"
    OAUTH_ACCOUNT_ALREADY_EXISTS = "oauth account already exists"
    OAUTH_ACCOUNT_NOT_SET = "oauth account not set"
