#!/bin/bash

export PREFIX="poetry run"
export SOURCE_FILES="fastapi_auth"

set -x

${PREFIX} flake8 $SOURCE_FILES --ignore=E501,W503 --exclude=__init__.py
${PREFIX} black --check --diff $SOURCE_FILES
${PREFIX} mypy $SOURCE_FILES